services:
  question-service:
    container_name: questionService
    build: 
      context: ./services/questionService
    env_file:
      - .env
    volumes:
      - ./services/questionService:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  user-service:
    container_name: clientService
    build: 
      context: ./services/clientService
    env_file:
      - .env
    volumes:
      - ./services/clientService:/app
      - /app/node_modules
    ports:
      - 5001:5000
      - 9230:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5433
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
